steps:

  - id: install
    name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - id: deploy
    name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['deploy','--only','functions']
    env:
      - 'FIREBASE_TOKEN=$_FIREBASE_TOKEN'

substitutions:
  _FIREBASE_TOKEN: token